# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site
name: "Association CryptoFR"
title: "Association CryptoFR"
description: "Site web officiel de l'association CryptoFR"
meta_description: "Site web officiel de l'association CryptoFR."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/assocrypto.fr'
email: 'asso@cryptofr.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  ffmad:
    name: ffmad
    display_name: ffmad
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: asso@cryptofr.com
    web: https://cryptofr.com
    twitter: https://twitter.com/CryptoFR
    description: "Président de l'association CryptoFR."
  lexyon:
    name: lexyon
    display_name: lexyon
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: asso@cryptofr.com
    web: https://cryptofr.com
    twitter: https://twitter.com/CryptoFR
    description: "Trésorière de l'association CryptoFR."

#theme: minima
remote_theme: wowthemesnet/affiliates-jekyll-theme

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/assocrypto.fr/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
